import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowLeft,Copy,Pause,Play,RotateCcw,Layers,Radio,SlidersHorizontal} from 'lucide-react';
import './perpcopier.css';
const accounts=[['Silver eval','Leader · you trade here','$4,991.26','+$41.26',1],['Silver 2-step','Follower','$4,985.05','+$20.63',0.5],['Gold eval','Follower','$9,962.10','+$41.30',1],['Gold funded','Follower','$10,214.88','+$4.13',0.1]];
export default function PerpCopier(){
 const [paused,setPaused]=useState(false),[flat,setFlat]=useState(false),[sizes,setSizes]=useState([1,0.5,1,0.1]);
 useEffect(()=>{const title=document.title;document.title='PerpCopier · MASSIVE';return()=>{document.title=title}},[]);
 const reset=()=>{setFlat(false);setPaused(false);setSizes([1,0.5,1,0.1])};
 return <main className="pc-page">
  <header className="pc-nav"><a className="pc-brand" href="#">MASSIVE<span>.</span></a><span className="pc-nav-label">THE TOOLKIT / 01</span><a href="#leaderboard"><ArrowLeft size={14}/> Leaderboard</a></header>
  <div className="pc-wrap">
   <section className="pc-hero">
    <h1>No account<br/><em>left behind.</em></h1><p className="pc-intro">Your trades. At your size. Across your Vest accounts.</p><div className="pc-actions"><a className="pc-primary" href="https://perpcopier.com/signin" target="_blank" rel="noopener noreferrer">Explore the beta <ArrowUpRight size={17}/></a><button onClick={()=>document.getElementById('pc-demo').scrollIntoView({behavior:'smooth'})}>Try the preview <span>↓</span></button></div>
   </section>
   <section className="pc-console" id="pc-demo" aria-label="Interactive example dashboard">
    <div className="pc-console-head"><div><Copy size={18}/><strong>perpcopier<span>.</span></strong><span className="pc-example">EXAMPLE DASHBOARD</span></div><span className="pc-status" role="status"><i/>{flat?'Demo flattened':paused?'Demo paused':'Demo copying'}</span></div>
    <div className="pc-table-scroll"><table><thead><tr><th>ACCOUNT</th><th>EQUITY</th><th>TODAY</th><th>SIZE</th><th>POSITION · ETH</th></tr></thead><tbody>{accounts.map(([name,role,equity,pnl],i)=><tr key={name} className={i===0?'pc-leader':''}><td><div className="pc-account"><Copy size={16}/><div><strong>{name}</strong><small>{role}</small></div></div></td><td>{equity}</td><td className="pc-profit">{pnl}</td><td>{i===0?<span className="pc-lead-label">LEADER</span>:<select aria-label={`${name} size multiplier`} value={sizes[i]} disabled={flat} onChange={e=>setSizes(old=>old.map((v,j)=>j===i?Number(e.target.value):v))}>{[0.1,0.5,1,2].map(v=><option key={v} value={v}>{v}×</option>)}</select>}</td><td>{flat?<span className="pc-dim">Flat</span>:<>Long {(0.5*sizes[i]).toFixed(2)}</>}</td></tr>)}<tr className="pc-excluded"><td><div className="pc-account"><span className="pc-empty"/><div><strong>Your own USDC</strong><small>Not enrolled in this example</small></div></div></td><td>—</td><td>—</td><td>OFF</td><td>—</td></tr></tbody></table></div>
    <div className="pc-console-foot"><div><span className="pc-mini">{flat?'ALL EXAMPLE POSITIONS CLOSED':paused?'NEW EXAMPLE COPIES PAUSED':'ETH LONG → 3 FOLLOWERS'}</span><p>Sample data. These controls only change this preview.</p></div><div className="pc-controls"><button onClick={reset} aria-label="Reset demo" title="Reset demo"><RotateCcw size={15}/></button><button disabled={flat} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'Resume':'Pause'}</button><button className="pc-flatten" disabled={flat} onClick={()=>{setFlat(true);setPaused(true)}}>Flatten demo</button></div></div>
   </section>
   <div className="pc-stats"><div><strong>01 <em>→ 09</em></strong><span>Leader to followers</span></div><div><strong>Your <em>size.</em></strong><span>Set each account independently</span></div><div><strong>Always <em>on.</em></strong><span>Server-side copying</span></div></div>
   <section className="pc-details"><h2>Trade once.<br/><span>Keep your own proportions.</span></h2><div className="pc-features">{[[Layers,'Choose your accounts','Pick one leader and the eval or funded Vest accounts that follow.'],[SlidersHorizontal,'Set the size','Use a different multiplier for each follower. Keep the setup yours.'],[Radio,'Leave it running','PerpCopier runs on its servers, so copying continues with your browser closed.']].map(([Icon,title,copy],i)=><article key={title}><div><Icon size={20}/><span>0{i+1}</span></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
   <section className="pc-beta"><div><h2>Meet your<br/><em>other accounts.</em></h2><p>Free during beta, according to PerpCopier.<br/>Connect and manage your accounts on their platform.</p></div><a className="pc-primary" href="https://perpcopier.com/signin" target="_blank" rel="noopener noreferrer">Open PerpCopier <ArrowUpRight size={17}/></a></section>
   <footer className="pc-footer"><p>Product preview · No accounts connected to MASSIVE.</p><p>Product details supplied by <a href="https://perpcopier.com/" target="_blank" rel="noopener noreferrer">PerpCopier ↗</a>. Its connection uses a Vest token with trading access across the login, including real-funds accounts; PerpCopier says it only trades enrolled accounts and cannot withdraw. Review its <a href="https://perpcopier.com/terms" target="_blank" rel="noopener noreferrer">terms</a> before connecting.</p><div><a className="pc-brand" href="#">MASSIVE<span>.</span></a></div></footer>
  </div>
 </main>
}
